# Generated by Django 4.2.2 on 2023-06-29 15:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_alter_user_avatar"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="currency",
            field=models.CharField(
                blank=True,
                choices=[
                    ("usd", "USD"),
                    ("kre", "KRW"),
                    ("inr", "INR"),
                    ("eur", "EUR"),
                    ("esp", "ESP"),
                ],
                max_length=3,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="language",
            field=models.CharField(
                blank=True,
                choices=[
                    ("en", "English"),
                    ("kr", "Korean"),
                    ("es", "Spanish"),
                    ("fr", "French"),
                    ("de", "German"),
                ],
                max_length=2,
            ),
        ),
    ]
