# Generated by Django 4.2.3 on 2023-07-27 18:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0006_user_email_confirmed_user_email_secret"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="login_method",
            field=models.CharField(
                choices=[
                    ("email", "Email"),
                    ("github", "Github"),
                    ("google", "Google"),
                ],
                default="email",
                max_length=50,
            ),
        ),
    ]
