# Generated by Django 4.2.3 on 2023-07-29 12:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0007_user_login_method"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="first_name",
            field=models.CharField(
                blank=True,
                default="Unnamed User",
                max_length=30,
                verbose_name="first name",
            ),
        ),
    ]
