# Generated by Django 4.2 on 2023-06-21 13:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rooms", "0005_alter_amenity_options_alter_facility_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="room",
            name="guest",
            field=models.IntegerField(default=0),
        ),
    ]
