# Generated by Django 4.2 on 2023-06-24 17:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rooms", "0009_alter_photo_room"),
    ]

    operations = [
        migrations.AlterField(
            model_name="photo",
            name="file",
            field=models.ImageField(upload_to="room_phostos"),
        ),
    ]
