# Generated by Django 4.2.2 on 2023-06-29 15:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rooms", "0010_alter_photo_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="photo",
            name="file",
            field=models.ImageField(upload_to="room_photos"),
        ),
    ]
