# Generated by Django 4.2.3 on 2023-07-23 14:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rooms", "0011_alter_photo_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="room",
            name="guest",
            field=models.IntegerField(default=0, help_text="Guest Count ?"),
        ),
    ]
